// <auto-generated />
using System;
using AlertDengueApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlertDengueApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106033735_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AlertDengueApi.Models.DengueAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccumulatedNotifications")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "notif_accum_year");

                    b.Property<int>("AlertLevel")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "nivel");

                    b.Property<int>("EpidemiologicalWeek")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "SE");

                    b.Property<double>("EstimatedCases")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "casos_est");

                    b.Property<double>("EstimatedCasesMax")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "casos_est_max");

                    b.Property<double>("EstimatedCasesMin")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "casos_est_min");

                    b.Property<double>("HumidityAvg")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "umidmed");

                    b.Property<double>("HumidityMax")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "umidmax");

                    b.Property<double>("HumidityMin")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "umidmin");

                    b.Property<int>("IncidenceLevel")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "nivel_inc");

                    b.Property<double>("IncidencePer100k")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "p_inc100k");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "versao_modelo");

                    b.Property<double>("Population")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "pop");

                    b.Property<double>("ProbabilityRtAbove1")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "p_rt1");

                    b.Property<int>("Receptivity")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "receptivo");

                    b.Property<int>("ReportedCases")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "casos");

                    b.Property<double>("Rt")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "Rt");

                    b.Property<DateTime>("StartOfEpiWeek")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "data_ini_SE");

                    b.Property<double>("TempAvg")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "tempmed");

                    b.Property<double>("TempMax")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "tempmax");

                    b.Property<double>("TempMin")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "tempmin");

                    b.Property<int>("Transmission")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "transmissao");

                    b.HasKey("Id");

                    b.HasIndex("EpidemiologicalWeek")
                        .IsUnique();

                    b.ToTable("DengueAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
